name: remote deploy

on: [push]
jobs:
    build:
        name: DEPLOY
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.0.0
              with:
                  command_timeout: 30m
                  host: 8.219.239.133
                  username: root
                  key: ${{ secrets.KEY }}
                  script: |
                      cd project/dify/docker
                      git pull
                      docker system prune -f
                      docker compose up  --no-deps --build -d
